/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardVotingRouteImport } from './routes/dashboard/voting'
import { Route as DashboardUtilitiesRouteImport } from './routes/dashboard/utilities'
import { Route as DashboardUnitsRouteImport } from './routes/dashboard/units'
import { Route as DashboardTodosRouteImport } from './routes/dashboard/todos'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTownhallsIndexRouteImport } from './routes/dashboard/townhalls/index'
import { Route as DashboardProposalsIndexRouteImport } from './routes/dashboard/proposals/index'
import { Route as DashboardUsersNewRouteImport } from './routes/dashboard/users/new'
import { Route as DashboardUsersUseridRouteImport } from './routes/dashboard/users/$userid'
import { Route as DashboardProposalsNewRouteImport } from './routes/dashboard/proposals/new'
import { Route as DashboardTownhallsOrgIdIndexRouteImport } from './routes/dashboard/townhalls/$orgId/index'
import { Route as DashboardTownhallsOrgIdMembersRouteImport } from './routes/dashboard/townhalls/$orgId/members'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardVotingRoute = DashboardVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUtilitiesRoute = DashboardUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUnitsRoute = DashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTodosRoute = DashboardTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTownhallsIndexRoute = DashboardTownhallsIndexRouteImport.update({
  id: '/townhalls/',
  path: '/townhalls/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProposalsIndexRoute = DashboardProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUsersNewRoute = DashboardUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUsersUseridRoute = DashboardUsersUseridRouteImport.update({
  id: '/users/$userid',
  path: '/users/$userid',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProposalsNewRoute = DashboardProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTownhallsOrgIdIndexRoute =
  DashboardTownhallsOrgIdIndexRouteImport.update({
    id: '/townhalls/$orgId/',
    path: '/townhalls/$orgId/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardTownhallsOrgIdMembersRoute =
  DashboardTownhallsOrgIdMembersRouteImport.update({
    id: '/townhalls/$orgId/members',
    path: '/townhalls/$orgId/members',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/dashboard/voting': typeof DashboardVotingRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/dashboard/users/$userid': typeof DashboardUsersUseridRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/proposals': typeof DashboardProposalsIndexRoute
  '/dashboard/townhalls': typeof DashboardTownhallsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/townhalls/$orgId/members': typeof DashboardTownhallsOrgIdMembersRoute
  '/dashboard/townhalls/$orgId': typeof DashboardTownhallsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/dashboard/voting': typeof DashboardVotingRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/dashboard/users/$userid': typeof DashboardUsersUseridRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/proposals': typeof DashboardProposalsIndexRoute
  '/dashboard/townhalls': typeof DashboardTownhallsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/townhalls/$orgId/members': typeof DashboardTownhallsOrgIdMembersRoute
  '/dashboard/townhalls/$orgId': typeof DashboardTownhallsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/dashboard/voting': typeof DashboardVotingRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/proposals/new': typeof DashboardProposalsNewRoute
  '/dashboard/users/$userid': typeof DashboardUsersUseridRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/proposals/': typeof DashboardProposalsIndexRoute
  '/dashboard/townhalls/': typeof DashboardTownhallsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/townhalls/$orgId/members': typeof DashboardTownhallsOrgIdMembersRoute
  '/dashboard/townhalls/$orgId/': typeof DashboardTownhallsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/signup'
    | '/dashboard/audit'
    | '/dashboard/members'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/dashboard/voting'
    | '/auth/'
    | '/dashboard/'
    | '/profile'
    | '/dashboard/proposals/new'
    | '/dashboard/users/$userid'
    | '/dashboard/users/new'
    | '/dashboard/proposals'
    | '/dashboard/townhalls'
    | '/dashboard/users'
    | '/dashboard/townhalls/$orgId/members'
    | '/dashboard/townhalls/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signup'
    | '/dashboard/audit'
    | '/dashboard/members'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/dashboard/voting'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/dashboard/proposals/new'
    | '/dashboard/users/$userid'
    | '/dashboard/users/new'
    | '/dashboard/proposals'
    | '/dashboard/townhalls'
    | '/dashboard/users'
    | '/dashboard/townhalls/$orgId/members'
    | '/dashboard/townhalls/$orgId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/signup'
    | '/dashboard/audit'
    | '/dashboard/members'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/dashboard/voting'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/proposals/new'
    | '/dashboard/users/$userid'
    | '/dashboard/users/new'
    | '/dashboard/proposals/'
    | '/dashboard/townhalls/'
    | '/dashboard/users/'
    | '/dashboard/townhalls/$orgId/members'
    | '/dashboard/townhalls/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/voting': {
      id: '/dashboard/voting'
      path: '/voting'
      fullPath: '/dashboard/voting'
      preLoaderRoute: typeof DashboardVotingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/utilities': {
      id: '/dashboard/utilities'
      path: '/utilities'
      fullPath: '/dashboard/utilities'
      preLoaderRoute: typeof DashboardUtilitiesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/units': {
      id: '/dashboard/units'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/todos': {
      id: '/dashboard/todos'
      path: '/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardTodosRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/townhalls/': {
      id: '/dashboard/townhalls/'
      path: '/townhalls'
      fullPath: '/dashboard/townhalls'
      preLoaderRoute: typeof DashboardTownhallsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/proposals/': {
      id: '/dashboard/proposals/'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/users/new': {
      id: '/dashboard/users/new'
      path: '/users/new'
      fullPath: '/dashboard/users/new'
      preLoaderRoute: typeof DashboardUsersNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/users/$userid': {
      id: '/dashboard/users/$userid'
      path: '/users/$userid'
      fullPath: '/dashboard/users/$userid'
      preLoaderRoute: typeof DashboardUsersUseridRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/proposals/new': {
      id: '/dashboard/proposals/new'
      path: '/proposals/new'
      fullPath: '/dashboard/proposals/new'
      preLoaderRoute: typeof DashboardProposalsNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/townhalls/$orgId/': {
      id: '/dashboard/townhalls/$orgId/'
      path: '/townhalls/$orgId'
      fullPath: '/dashboard/townhalls/$orgId'
      preLoaderRoute: typeof DashboardTownhallsOrgIdIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/townhalls/$orgId/members': {
      id: '/dashboard/townhalls/$orgId/members'
      path: '/townhalls/$orgId/members'
      fullPath: '/dashboard/townhalls/$orgId/members'
      preLoaderRoute: typeof DashboardTownhallsOrgIdMembersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardTodosRoute: typeof DashboardTodosRoute
  DashboardUnitsRoute: typeof DashboardUnitsRoute
  DashboardUtilitiesRoute: typeof DashboardUtilitiesRoute
  DashboardVotingRoute: typeof DashboardVotingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProposalsNewRoute: typeof DashboardProposalsNewRoute
  DashboardUsersUseridRoute: typeof DashboardUsersUseridRoute
  DashboardUsersNewRoute: typeof DashboardUsersNewRoute
  DashboardProposalsIndexRoute: typeof DashboardProposalsIndexRoute
  DashboardTownhallsIndexRoute: typeof DashboardTownhallsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardTownhallsOrgIdMembersRoute: typeof DashboardTownhallsOrgIdMembersRoute
  DashboardTownhallsOrgIdIndexRoute: typeof DashboardTownhallsOrgIdIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardTodosRoute: DashboardTodosRoute,
  DashboardUnitsRoute: DashboardUnitsRoute,
  DashboardUtilitiesRoute: DashboardUtilitiesRoute,
  DashboardVotingRoute: DashboardVotingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProposalsNewRoute: DashboardProposalsNewRoute,
  DashboardUsersUseridRoute: DashboardUsersUseridRoute,
  DashboardUsersNewRoute: DashboardUsersNewRoute,
  DashboardProposalsIndexRoute: DashboardProposalsIndexRoute,
  DashboardTownhallsIndexRoute: DashboardTownhallsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardTownhallsOrgIdMembersRoute: DashboardTownhallsOrgIdMembersRoute,
  DashboardTownhallsOrgIdIndexRoute: DashboardTownhallsOrgIdIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
