/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardUserLayoutRouteImport } from './routes/dashboard/user/layout'
import { Route as DashboardStaffLayoutRouteImport } from './routes/dashboard/staff/layout'
import { Route as DashboardOwnerLayoutRouteImport } from './routes/dashboard/owner/layout'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard/user/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardOwnerIndexRouteImport } from './routes/dashboard/owner/index'
import { Route as DashboardUserReviewsRouteImport } from './routes/dashboard/user/reviews'
import { Route as DashboardUserProfileRouteImport } from './routes/dashboard/user/profile'
import { Route as DashboardUserOrdersRouteImport } from './routes/dashboard/user/orders'
import { Route as DashboardUserKitchensRouteImport } from './routes/dashboard/user/kitchens'
import { Route as DashboardUserFavoritesRouteImport } from './routes/dashboard/user/favorites'
import { Route as DashboardStaffReviewsRouteImport } from './routes/dashboard/staff/reviews'
import { Route as DashboardStaffProfileRouteImport } from './routes/dashboard/staff/profile'
import { Route as DashboardStaffOrdersRouteImport } from './routes/dashboard/staff/orders'
import { Route as DashboardStaffMenuRouteImport } from './routes/dashboard/staff/menu'
import { Route as DashboardStaffMembersRouteImport } from './routes/dashboard/staff/members'
import { Route as DashboardOwnerStaffRouteImport } from './routes/dashboard/owner/staff'
import { Route as DashboardOwnerReviewsRouteImport } from './routes/dashboard/owner/reviews'
import { Route as DashboardOwnerProfileRouteImport } from './routes/dashboard/owner/profile'
import { Route as DashboardOwnerOrdersRouteImport } from './routes/dashboard/owner/orders'
import { Route as DashboardOwnerMenuRouteImport } from './routes/dashboard/owner/menu'
import { Route as DashboardOwnerAuditRouteImport } from './routes/dashboard/owner/audit'
import { Route as DashboardOwnerUsersIndexRouteImport } from './routes/dashboard/owner/users/index'
import { Route as DashboardOwnerKitchensIndexRouteImport } from './routes/dashboard/owner/kitchens/index'
import { Route as DashboardOwnerUsersNewRouteImport } from './routes/dashboard/owner/users/new'
import { Route as DashboardOwnerUsersUseridRouteImport } from './routes/dashboard/owner/users/$userid'
import { Route as DashboardOwnerOnboardingKitchenIndexRouteImport } from './routes/dashboard/owner/onboarding/kitchen/index'
import { Route as DashboardOwnerKitchensOrgIdIndexRouteImport } from './routes/dashboard/owner/kitchens/$orgId/index'
import { Route as DashboardOwnerKitchensOrgIdMembersRouteImport } from './routes/dashboard/owner/kitchens/$orgId/members'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardUserLayoutRoute = DashboardUserLayoutRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffLayoutRoute = DashboardStaffLayoutRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardOwnerLayoutRoute = DashboardOwnerLayoutRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardOwnerIndexRoute = DashboardOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardUserReviewsRoute = DashboardUserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserProfileRoute = DashboardUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserOrdersRoute = DashboardUserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserKitchensRoute = DashboardUserKitchensRouteImport.update({
  id: '/kitchens',
  path: '/kitchens',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardUserFavoritesRoute = DashboardUserFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardUserLayoutRoute,
} as any)
const DashboardStaffReviewsRoute = DashboardStaffReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardStaffProfileRoute = DashboardStaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardStaffOrdersRoute = DashboardStaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardStaffMenuRoute = DashboardStaffMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardStaffMembersRoute = DashboardStaffMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardStaffLayoutRoute,
} as any)
const DashboardOwnerStaffRoute = DashboardOwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerReviewsRoute = DashboardOwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerProfileRoute = DashboardOwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerOrdersRoute = DashboardOwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerMenuRoute = DashboardOwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerAuditRoute = DashboardOwnerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerUsersIndexRoute =
  DashboardOwnerUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)
const DashboardOwnerKitchensIndexRoute =
  DashboardOwnerKitchensIndexRouteImport.update({
    id: '/kitchens/',
    path: '/kitchens/',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)
const DashboardOwnerUsersNewRoute = DashboardOwnerUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => DashboardOwnerLayoutRoute,
} as any)
const DashboardOwnerUsersUseridRoute =
  DashboardOwnerUsersUseridRouteImport.update({
    id: '/users/$userid',
    path: '/users/$userid',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)
const DashboardOwnerOnboardingKitchenIndexRoute =
  DashboardOwnerOnboardingKitchenIndexRouteImport.update({
    id: '/onboarding/kitchen/',
    path: '/onboarding/kitchen/',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)
const DashboardOwnerKitchensOrgIdIndexRoute =
  DashboardOwnerKitchensOrgIdIndexRouteImport.update({
    id: '/kitchens/$orgId/',
    path: '/kitchens/$orgId/',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)
const DashboardOwnerKitchensOrgIdMembersRoute =
  DashboardOwnerKitchensOrgIdMembersRouteImport.update({
    id: '/kitchens/$orgId/members',
    path: '/kitchens/$orgId/members',
    getParentRoute: () => DashboardOwnerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/search': typeof SearchRoute
  '/dashboard/owner': typeof DashboardOwnerLayoutRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffLayoutRouteWithChildren
  '/dashboard/user': typeof DashboardUserLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/owner/audit': typeof DashboardOwnerAuditRoute
  '/dashboard/owner/menu': typeof DashboardOwnerMenuRoute
  '/dashboard/owner/orders': typeof DashboardOwnerOrdersRoute
  '/dashboard/owner/profile': typeof DashboardOwnerProfileRoute
  '/dashboard/owner/reviews': typeof DashboardOwnerReviewsRoute
  '/dashboard/owner/staff': typeof DashboardOwnerStaffRoute
  '/dashboard/staff/members': typeof DashboardStaffMembersRoute
  '/dashboard/staff/menu': typeof DashboardStaffMenuRoute
  '/dashboard/staff/orders': typeof DashboardStaffOrdersRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/reviews': typeof DashboardStaffReviewsRoute
  '/dashboard/user/favorites': typeof DashboardUserFavoritesRoute
  '/dashboard/user/kitchens': typeof DashboardUserKitchensRoute
  '/dashboard/user/orders': typeof DashboardUserOrdersRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/owner/': typeof DashboardOwnerIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
  '/dashboard/owner/users/$userid': typeof DashboardOwnerUsersUseridRoute
  '/dashboard/owner/users/new': typeof DashboardOwnerUsersNewRoute
  '/dashboard/owner/kitchens/': typeof DashboardOwnerKitchensIndexRoute
  '/dashboard/owner/users/': typeof DashboardOwnerUsersIndexRoute
  '/dashboard/owner/kitchens/$orgId/members': typeof DashboardOwnerKitchensOrgIdMembersRoute
  '/dashboard/owner/kitchens/$orgId/': typeof DashboardOwnerKitchensOrgIdIndexRoute
  '/dashboard/owner/onboarding/kitchen/': typeof DashboardOwnerOnboardingKitchenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/owner/audit': typeof DashboardOwnerAuditRoute
  '/dashboard/owner/menu': typeof DashboardOwnerMenuRoute
  '/dashboard/owner/orders': typeof DashboardOwnerOrdersRoute
  '/dashboard/owner/profile': typeof DashboardOwnerProfileRoute
  '/dashboard/owner/reviews': typeof DashboardOwnerReviewsRoute
  '/dashboard/owner/staff': typeof DashboardOwnerStaffRoute
  '/dashboard/staff/members': typeof DashboardStaffMembersRoute
  '/dashboard/staff/menu': typeof DashboardStaffMenuRoute
  '/dashboard/staff/orders': typeof DashboardStaffOrdersRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/reviews': typeof DashboardStaffReviewsRoute
  '/dashboard/user/favorites': typeof DashboardUserFavoritesRoute
  '/dashboard/user/kitchens': typeof DashboardUserKitchensRoute
  '/dashboard/user/orders': typeof DashboardUserOrdersRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/owner': typeof DashboardOwnerIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/user': typeof DashboardUserIndexRoute
  '/dashboard/owner/users/$userid': typeof DashboardOwnerUsersUseridRoute
  '/dashboard/owner/users/new': typeof DashboardOwnerUsersNewRoute
  '/dashboard/owner/kitchens': typeof DashboardOwnerKitchensIndexRoute
  '/dashboard/owner/users': typeof DashboardOwnerUsersIndexRoute
  '/dashboard/owner/kitchens/$orgId/members': typeof DashboardOwnerKitchensOrgIdMembersRoute
  '/dashboard/owner/kitchens/$orgId': typeof DashboardOwnerKitchensOrgIdIndexRoute
  '/dashboard/owner/onboarding/kitchen': typeof DashboardOwnerOnboardingKitchenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/search': typeof SearchRoute
  '/dashboard/owner': typeof DashboardOwnerLayoutRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffLayoutRouteWithChildren
  '/dashboard/user': typeof DashboardUserLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/owner/audit': typeof DashboardOwnerAuditRoute
  '/dashboard/owner/menu': typeof DashboardOwnerMenuRoute
  '/dashboard/owner/orders': typeof DashboardOwnerOrdersRoute
  '/dashboard/owner/profile': typeof DashboardOwnerProfileRoute
  '/dashboard/owner/reviews': typeof DashboardOwnerReviewsRoute
  '/dashboard/owner/staff': typeof DashboardOwnerStaffRoute
  '/dashboard/staff/members': typeof DashboardStaffMembersRoute
  '/dashboard/staff/menu': typeof DashboardStaffMenuRoute
  '/dashboard/staff/orders': typeof DashboardStaffOrdersRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/reviews': typeof DashboardStaffReviewsRoute
  '/dashboard/user/favorites': typeof DashboardUserFavoritesRoute
  '/dashboard/user/kitchens': typeof DashboardUserKitchensRoute
  '/dashboard/user/orders': typeof DashboardUserOrdersRoute
  '/dashboard/user/profile': typeof DashboardUserProfileRoute
  '/dashboard/user/reviews': typeof DashboardUserReviewsRoute
  '/dashboard/owner/': typeof DashboardOwnerIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
  '/dashboard/owner/users/$userid': typeof DashboardOwnerUsersUseridRoute
  '/dashboard/owner/users/new': typeof DashboardOwnerUsersNewRoute
  '/dashboard/owner/kitchens/': typeof DashboardOwnerKitchensIndexRoute
  '/dashboard/owner/users/': typeof DashboardOwnerUsersIndexRoute
  '/dashboard/owner/kitchens/$orgId/members': typeof DashboardOwnerKitchensOrgIdMembersRoute
  '/dashboard/owner/kitchens/$orgId/': typeof DashboardOwnerKitchensOrgIdIndexRoute
  '/dashboard/owner/onboarding/kitchen/': typeof DashboardOwnerOnboardingKitchenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/search'
    | '/dashboard/owner'
    | '/dashboard/staff'
    | '/dashboard/user'
    | '/auth/signup'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/owner/audit'
    | '/dashboard/owner/menu'
    | '/dashboard/owner/orders'
    | '/dashboard/owner/profile'
    | '/dashboard/owner/reviews'
    | '/dashboard/owner/staff'
    | '/dashboard/staff/members'
    | '/dashboard/staff/menu'
    | '/dashboard/staff/orders'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/reviews'
    | '/dashboard/user/favorites'
    | '/dashboard/user/kitchens'
    | '/dashboard/user/orders'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/owner/'
    | '/dashboard/staff/'
    | '/dashboard/user/'
    | '/dashboard/owner/users/$userid'
    | '/dashboard/owner/users/new'
    | '/dashboard/owner/kitchens/'
    | '/dashboard/owner/users/'
    | '/dashboard/owner/kitchens/$orgId/members'
    | '/dashboard/owner/kitchens/$orgId/'
    | '/dashboard/owner/onboarding/kitchen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/auth/signup'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/dashboard/owner/audit'
    | '/dashboard/owner/menu'
    | '/dashboard/owner/orders'
    | '/dashboard/owner/profile'
    | '/dashboard/owner/reviews'
    | '/dashboard/owner/staff'
    | '/dashboard/staff/members'
    | '/dashboard/staff/menu'
    | '/dashboard/staff/orders'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/reviews'
    | '/dashboard/user/favorites'
    | '/dashboard/user/kitchens'
    | '/dashboard/user/orders'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/owner'
    | '/dashboard/staff'
    | '/dashboard/user'
    | '/dashboard/owner/users/$userid'
    | '/dashboard/owner/users/new'
    | '/dashboard/owner/kitchens'
    | '/dashboard/owner/users'
    | '/dashboard/owner/kitchens/$orgId/members'
    | '/dashboard/owner/kitchens/$orgId'
    | '/dashboard/owner/onboarding/kitchen'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/search'
    | '/dashboard/owner'
    | '/dashboard/staff'
    | '/dashboard/user'
    | '/auth/signup'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/owner/audit'
    | '/dashboard/owner/menu'
    | '/dashboard/owner/orders'
    | '/dashboard/owner/profile'
    | '/dashboard/owner/reviews'
    | '/dashboard/owner/staff'
    | '/dashboard/staff/members'
    | '/dashboard/staff/menu'
    | '/dashboard/staff/orders'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/reviews'
    | '/dashboard/user/favorites'
    | '/dashboard/user/kitchens'
    | '/dashboard/user/orders'
    | '/dashboard/user/profile'
    | '/dashboard/user/reviews'
    | '/dashboard/owner/'
    | '/dashboard/staff/'
    | '/dashboard/user/'
    | '/dashboard/owner/users/$userid'
    | '/dashboard/owner/users/new'
    | '/dashboard/owner/kitchens/'
    | '/dashboard/owner/users/'
    | '/dashboard/owner/kitchens/$orgId/members'
    | '/dashboard/owner/kitchens/$orgId/'
    | '/dashboard/owner/onboarding/kitchen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/owner/': {
      id: '/dashboard/owner/'
      path: '/'
      fullPath: '/dashboard/owner/'
      preLoaderRoute: typeof DashboardOwnerIndexRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/user/reviews': {
      id: '/dashboard/user/reviews'
      path: '/reviews'
      fullPath: '/dashboard/user/reviews'
      preLoaderRoute: typeof DashboardUserReviewsRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/user/profile': {
      id: '/dashboard/user/profile'
      path: '/profile'
      fullPath: '/dashboard/user/profile'
      preLoaderRoute: typeof DashboardUserProfileRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/user/orders': {
      id: '/dashboard/user/orders'
      path: '/orders'
      fullPath: '/dashboard/user/orders'
      preLoaderRoute: typeof DashboardUserOrdersRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/user/kitchens': {
      id: '/dashboard/user/kitchens'
      path: '/kitchens'
      fullPath: '/dashboard/user/kitchens'
      preLoaderRoute: typeof DashboardUserKitchensRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/user/favorites': {
      id: '/dashboard/user/favorites'
      path: '/favorites'
      fullPath: '/dashboard/user/favorites'
      preLoaderRoute: typeof DashboardUserFavoritesRouteImport
      parentRoute: typeof DashboardUserLayoutRoute
    }
    '/dashboard/staff/reviews': {
      id: '/dashboard/staff/reviews'
      path: '/reviews'
      fullPath: '/dashboard/staff/reviews'
      preLoaderRoute: typeof DashboardStaffReviewsRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/staff/profile': {
      id: '/dashboard/staff/profile'
      path: '/profile'
      fullPath: '/dashboard/staff/profile'
      preLoaderRoute: typeof DashboardStaffProfileRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/staff/orders': {
      id: '/dashboard/staff/orders'
      path: '/orders'
      fullPath: '/dashboard/staff/orders'
      preLoaderRoute: typeof DashboardStaffOrdersRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/staff/menu': {
      id: '/dashboard/staff/menu'
      path: '/menu'
      fullPath: '/dashboard/staff/menu'
      preLoaderRoute: typeof DashboardStaffMenuRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/staff/members': {
      id: '/dashboard/staff/members'
      path: '/members'
      fullPath: '/dashboard/staff/members'
      preLoaderRoute: typeof DashboardStaffMembersRouteImport
      parentRoute: typeof DashboardStaffLayoutRoute
    }
    '/dashboard/owner/staff': {
      id: '/dashboard/owner/staff'
      path: '/staff'
      fullPath: '/dashboard/owner/staff'
      preLoaderRoute: typeof DashboardOwnerStaffRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/reviews': {
      id: '/dashboard/owner/reviews'
      path: '/reviews'
      fullPath: '/dashboard/owner/reviews'
      preLoaderRoute: typeof DashboardOwnerReviewsRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/profile': {
      id: '/dashboard/owner/profile'
      path: '/profile'
      fullPath: '/dashboard/owner/profile'
      preLoaderRoute: typeof DashboardOwnerProfileRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/orders': {
      id: '/dashboard/owner/orders'
      path: '/orders'
      fullPath: '/dashboard/owner/orders'
      preLoaderRoute: typeof DashboardOwnerOrdersRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/menu': {
      id: '/dashboard/owner/menu'
      path: '/menu'
      fullPath: '/dashboard/owner/menu'
      preLoaderRoute: typeof DashboardOwnerMenuRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/audit': {
      id: '/dashboard/owner/audit'
      path: '/audit'
      fullPath: '/dashboard/owner/audit'
      preLoaderRoute: typeof DashboardOwnerAuditRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/users/': {
      id: '/dashboard/owner/users/'
      path: '/users'
      fullPath: '/dashboard/owner/users/'
      preLoaderRoute: typeof DashboardOwnerUsersIndexRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/kitchens/': {
      id: '/dashboard/owner/kitchens/'
      path: '/kitchens'
      fullPath: '/dashboard/owner/kitchens/'
      preLoaderRoute: typeof DashboardOwnerKitchensIndexRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/users/new': {
      id: '/dashboard/owner/users/new'
      path: '/users/new'
      fullPath: '/dashboard/owner/users/new'
      preLoaderRoute: typeof DashboardOwnerUsersNewRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/users/$userid': {
      id: '/dashboard/owner/users/$userid'
      path: '/users/$userid'
      fullPath: '/dashboard/owner/users/$userid'
      preLoaderRoute: typeof DashboardOwnerUsersUseridRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/onboarding/kitchen/': {
      id: '/dashboard/owner/onboarding/kitchen/'
      path: '/onboarding/kitchen'
      fullPath: '/dashboard/owner/onboarding/kitchen/'
      preLoaderRoute: typeof DashboardOwnerOnboardingKitchenIndexRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/kitchens/$orgId/': {
      id: '/dashboard/owner/kitchens/$orgId/'
      path: '/kitchens/$orgId'
      fullPath: '/dashboard/owner/kitchens/$orgId/'
      preLoaderRoute: typeof DashboardOwnerKitchensOrgIdIndexRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
    '/dashboard/owner/kitchens/$orgId/members': {
      id: '/dashboard/owner/kitchens/$orgId/members'
      path: '/kitchens/$orgId/members'
      fullPath: '/dashboard/owner/kitchens/$orgId/members'
      preLoaderRoute: typeof DashboardOwnerKitchensOrgIdMembersRouteImport
      parentRoute: typeof DashboardOwnerLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardOwnerLayoutRouteChildren {
  DashboardOwnerAuditRoute: typeof DashboardOwnerAuditRoute
  DashboardOwnerMenuRoute: typeof DashboardOwnerMenuRoute
  DashboardOwnerOrdersRoute: typeof DashboardOwnerOrdersRoute
  DashboardOwnerProfileRoute: typeof DashboardOwnerProfileRoute
  DashboardOwnerReviewsRoute: typeof DashboardOwnerReviewsRoute
  DashboardOwnerStaffRoute: typeof DashboardOwnerStaffRoute
  DashboardOwnerIndexRoute: typeof DashboardOwnerIndexRoute
  DashboardOwnerUsersUseridRoute: typeof DashboardOwnerUsersUseridRoute
  DashboardOwnerUsersNewRoute: typeof DashboardOwnerUsersNewRoute
  DashboardOwnerKitchensIndexRoute: typeof DashboardOwnerKitchensIndexRoute
  DashboardOwnerUsersIndexRoute: typeof DashboardOwnerUsersIndexRoute
  DashboardOwnerKitchensOrgIdMembersRoute: typeof DashboardOwnerKitchensOrgIdMembersRoute
  DashboardOwnerKitchensOrgIdIndexRoute: typeof DashboardOwnerKitchensOrgIdIndexRoute
  DashboardOwnerOnboardingKitchenIndexRoute: typeof DashboardOwnerOnboardingKitchenIndexRoute
}

const DashboardOwnerLayoutRouteChildren: DashboardOwnerLayoutRouteChildren = {
  DashboardOwnerAuditRoute: DashboardOwnerAuditRoute,
  DashboardOwnerMenuRoute: DashboardOwnerMenuRoute,
  DashboardOwnerOrdersRoute: DashboardOwnerOrdersRoute,
  DashboardOwnerProfileRoute: DashboardOwnerProfileRoute,
  DashboardOwnerReviewsRoute: DashboardOwnerReviewsRoute,
  DashboardOwnerStaffRoute: DashboardOwnerStaffRoute,
  DashboardOwnerIndexRoute: DashboardOwnerIndexRoute,
  DashboardOwnerUsersUseridRoute: DashboardOwnerUsersUseridRoute,
  DashboardOwnerUsersNewRoute: DashboardOwnerUsersNewRoute,
  DashboardOwnerKitchensIndexRoute: DashboardOwnerKitchensIndexRoute,
  DashboardOwnerUsersIndexRoute: DashboardOwnerUsersIndexRoute,
  DashboardOwnerKitchensOrgIdMembersRoute:
    DashboardOwnerKitchensOrgIdMembersRoute,
  DashboardOwnerKitchensOrgIdIndexRoute: DashboardOwnerKitchensOrgIdIndexRoute,
  DashboardOwnerOnboardingKitchenIndexRoute:
    DashboardOwnerOnboardingKitchenIndexRoute,
}

const DashboardOwnerLayoutRouteWithChildren =
  DashboardOwnerLayoutRoute._addFileChildren(DashboardOwnerLayoutRouteChildren)

interface DashboardStaffLayoutRouteChildren {
  DashboardStaffMembersRoute: typeof DashboardStaffMembersRoute
  DashboardStaffMenuRoute: typeof DashboardStaffMenuRoute
  DashboardStaffOrdersRoute: typeof DashboardStaffOrdersRoute
  DashboardStaffProfileRoute: typeof DashboardStaffProfileRoute
  DashboardStaffReviewsRoute: typeof DashboardStaffReviewsRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
}

const DashboardStaffLayoutRouteChildren: DashboardStaffLayoutRouteChildren = {
  DashboardStaffMembersRoute: DashboardStaffMembersRoute,
  DashboardStaffMenuRoute: DashboardStaffMenuRoute,
  DashboardStaffOrdersRoute: DashboardStaffOrdersRoute,
  DashboardStaffProfileRoute: DashboardStaffProfileRoute,
  DashboardStaffReviewsRoute: DashboardStaffReviewsRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
}

const DashboardStaffLayoutRouteWithChildren =
  DashboardStaffLayoutRoute._addFileChildren(DashboardStaffLayoutRouteChildren)

interface DashboardUserLayoutRouteChildren {
  DashboardUserFavoritesRoute: typeof DashboardUserFavoritesRoute
  DashboardUserKitchensRoute: typeof DashboardUserKitchensRoute
  DashboardUserOrdersRoute: typeof DashboardUserOrdersRoute
  DashboardUserProfileRoute: typeof DashboardUserProfileRoute
  DashboardUserReviewsRoute: typeof DashboardUserReviewsRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardUserLayoutRouteChildren: DashboardUserLayoutRouteChildren = {
  DashboardUserFavoritesRoute: DashboardUserFavoritesRoute,
  DashboardUserKitchensRoute: DashboardUserKitchensRoute,
  DashboardUserOrdersRoute: DashboardUserOrdersRoute,
  DashboardUserProfileRoute: DashboardUserProfileRoute,
  DashboardUserReviewsRoute: DashboardUserReviewsRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardUserLayoutRouteWithChildren =
  DashboardUserLayoutRoute._addFileChildren(DashboardUserLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardOwnerLayoutRoute: typeof DashboardOwnerLayoutRouteWithChildren
  DashboardStaffLayoutRoute: typeof DashboardStaffLayoutRouteWithChildren
  DashboardUserLayoutRoute: typeof DashboardUserLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardOwnerLayoutRoute: DashboardOwnerLayoutRouteWithChildren,
  DashboardStaffLayoutRoute: DashboardStaffLayoutRouteWithChildren,
  DashboardUserLayoutRoute: DashboardUserLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  SearchRoute: SearchRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
